### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by hkdobrev** [clippings/ldf16-guide#13]
A favicon is always needed as browsers automatically request `/favicon.ico`.

I'd recommend following the [favicon cheatsheet](https://github.com/audreyr/favicon-cheat-sheet) and build several sizes into one file and also offer alternatives for maximum browser support and also best experience on retina displays.

``` html
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="icon" sizes="16x16 32x32 48x48" href="/favicon.ico">
<link rel="apple-touch-icon-precomposed" href="/favicon-152.png">
```

**Comment by thomdorkings** [comment]
Done in #21
