### ISSUE TITLE
Background image on homepage should be optimised

### ISSUE THREAD

**Issue by hkdobrev** [clippings/ldf16-guide#8]
The background image on the homepage is loading too slow. Normally that won't be such a problem, but in this case the layout seems broken until you realise this is in image which is still loading. I'd recommend to optimise the image and if it's still a problem on a slow connection we could show the image once it's loaded with JS.

**Comment by thomdorkings** [comment]
Yes, at the moment, no images have been optimised/resized. It's on my todo when we start populating with content.

**Comment by thomdorkings** [comment]
Fixed with #17
