### ISSUE TITLE
Layout on desktop

### ISSUE THREAD

**Issue by hkdobrev** [clippings/ldf16-guide#9]
I know this is specifically targeted at mobile users, but it's quite possible people open it from their emails on a desktop. It looks quite broken or at least too wide on desktop at the moment. I think it'd be best to add a couple of touches addressing that before launching it.

The biggest problem is the homepage where the image is so stretched you don't see the actual image.

For the rest of the pages we could just add a max width of the container if above certain threshold.

**Comment by thomdorkings** [comment]
Yeh, to be honest it's only been designed to be used as a mobile thing on the go.

My plan at the moment is to put a max-width on the body and show a message for users not on mobiles. If we had more time I'd make it look nice on all devices, but we're cutting it fine as it is!

**Comment by hkdobrev** [comment]
>  put a max-width on the body

That's exactly what I mean, this should be enough.

> show a message for users not on mobiles

👎  no need IMHO.

**Comment by hkdobrev** [comment]
Fixed in #10.

@thomdorkings BTW you can close issues through commit messages or pull requests. https://github.com/blog/1506-closing-issues-via-pull-requests The issue would be closed when the commit/PR is on the master branch.
